name: Build ODM Premium APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Buildozer Android Action
        uses: ArtemGovorov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer -v android debug
          buildozer_version: master

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ODM-Cyberpunk-App
          path: ${{ steps.buildozer.outputs.filename }}
